package exercicios.lista4;
/*
 * CRIE UM PROGRAMA ONDE O USUÁRIO IRÁ INFORMAR O VALOR DE CADA GASTO REALIZADO NO MÊS. OS
GASTOS DEVEM SER LANÇADOS DE ACORDO COM AS CATEGORIAS (ALIMENTAÇÃO, COMBUSTÍVEL E SAÚDE). AO
FINAL O PROGRAMA DEVE INFORMAR:
• O TOTAL GASTO NO MÊS;
• QUAL A CATEGORIA COM MAIS GASTOS;
• QUAL A CATEGORIA COM MENOS GASTOS;
 */
public class ex15 {
    
}
