package exercicios.lista4;
/*
 * FAÇA UM PROGRAMA QUE LEIA O VALOR DAS RECEITAS E DESPESAS DE UMA EMPRESA E EXIBA NA TELA O
RESULTADO DO MÊS DESSA EMPRESA. CASO O RESULTADO SEJA NEGATIVO EXIBA A MENSAGEM "A EMPRESA
FICOU NO PREJUÍZO ESSE MÊS", CASO CONTRÁRIO INFORME A MENSAGEM "TIVEMOS UM RESULTADO POSITIVO
ESSE MÊS".
 */
public class ex16 {
    
}
