package exercicios.lista4;
/*
 * UM EMPRESÁRIO DE TAXI AÉREO DESEJA SABER QUAL DAS SUAS AERONAVES É A MAIS ECONÔMICA. PARA
ISSO ELE LHE CONTRATOU PARA DESENVOLVER UM PROGRAMA QUE LEIA O MODELO, A DISTÂNCIA (EM KM) E O
COMBUSTÍVEL (EM LITROS) GASTO PELAS AERONAVES. DESEJA-SE SABER QUAL O MODELO E O CONSUMO DA
AERONAVE MAIS ECONÔMICA.
 */
public class ex17 {
    
}
