package exercicios.lista4;
/*
 * CRIE UM PROGRAMA QUE LEIA A QUANTIDADE DE CHUVA (EM MILÍMETRO) REGISTRADA EM UMA SEMANA E
EXIBA NA TELA A MÉDIA DE CHUVA POR DIA E CLASSIFIQUE O TEMPO CONFORME A TABELA ABAIXO:
CHUVA (MILÍMETRO) CLASSIFICAÇÃO
MENOR QUE 30 SECA
ENTRE 30 E 70 NORMAL
ACIMA DE 70 CHUVOSA
 */
public class ex18 {
    
}
